apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - name: {{ .Values.pnet.container.name }}-port
      protocol: TCP
      port: {{ .Values.pnet.container.port }}
      targetPort: {{ .Values.pnet.container.port }}
    - name: {{ .Values.gnet.container.name }}-port
      protocol: TCP
      port: {{ .Values.gnet.container.port }}
      targetPort: {{ .Values.gnet.container.port }}
  type: LoadBalancer
