apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
    spec:
      containers:
        - name: pnet-app
          image: narwaqazwsx/pnet-app
          ports:
            - containerPort: 8889
        - name: gnet-app
          image: narwaqazwsx/gnet-app
          ports:
            - containerPort: 8888
